
public class Javaexception {

	public static void main(String[] args) {
		
		
		
//		System.out.println("This is 1st line befor error ");
//		
//		try{
//			
//			int a =50/0;      // Arithmatic exception
//		
//		}
//		
//	
//		catch(Exception e) {
//		
//			System.out.println("This is an arithmatic exception error ");
//
//	    }
//		
//		
//		System.out.println("This is further program after error handling ");
//		

//		
//		int a[]= {1,2,3};              //Arrayindexoutofbound exception 
//		
//		System.out.println("number at the index 10 is "+a[10]);
//		
		
		
		
		String str=null;                 // Null pointer exception 
		
		System.out.println(str.length());
		
		
}
	
	
}